version: '3'

services:

  mysql-standalone:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=test
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=password
    ports:
      - 3306:3306

  shorten-url:
    build:
      context: .
      dockerfile: Dockerfile
    image: shorten-url
    restart: on-failure
    depends_on:
      - mysql-standalone ##can be changed to localhost
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql-standalone
      - DATABASE_USER=sa
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=test
      - DATABASE_PORT=3306